name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "adf_publish" ]
  pull_request:
    branches: [ "adf_publish" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy_UAT:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: UAT
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        with:
          resourceGroupName: Synapse
          template: adfsingle/ARMTemplateForFactory.json
          parameters: adfsingle/ARMTemplateForFactory.json factoryName=${{ env.FACTORY_NAME }}
  Deploy_Prod:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: Deploy_UAT
    environment: Production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        with:
          resourceGroupName: Synapse
          template: adfsingle/ARMTemplateForFactory.json
          parameters: adfsingle/ARMTemplateForFactory.json factoryName=${{ env.FACTORY_NAME }}
